# application.yml for UserService

spring:
  application:
    name: UserService
  mongo:
    uri: mongodb://localhost:27017/userdb

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Additional custom configuration (for UserService specific)
user-service:
  default-role: USER
  max-login-attempts: 5
  jwt:
    secret-key: supersecretkey
    expiration-time: 3600