server:
  port: 8888  # Port for the config server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/<user-name>/<repo-name>
          clone-on-start: true		
          password: <pwd>
          username: <user>
  application:
    name:    ConfigService       # Optionally, you can use a classpath location
          # search-locations: classpath:/config/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#spring.data.mongodb.uri=mongodb://localhost:27017/userdb
